name: Mulesoft CI
on: 
  pull_request:
    branches:  
      - main
env: 
   MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/mulesoft-github-actions"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
          server-id: maven # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: rortega-sps # env variable for username in deploy
          server-password: ${{ secrets.PACKAGES_TOKEN }} # env variable for token in deploy
      - name: 'Create settins.xml'
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          #repositories: '[{ "id": "github", "url": "http://some.repository.url" }]'
          #plugin_repositories: '[{ "id": "some-plugin-repository", "url": "http://some.plugin.repository.url" }]'
          servers: '[{ "id": "github", "username": "rortega-sps", "password": "${{ secrets.PACKAGES_TOKEN }}", "snapshots":{"enabled":"true"} }]'

      - run: |
         mvn --batch-mode verify
         mkdir staging && cp target/*.jar staging
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }} # GITHUB_TOKEN is the default env for the password
