name: Mulesoft CI Publish
on: 
  push:
    branches:  
      - main
env: 
   MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/mulesoft-github-actions"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: produccion
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: rortega-sps # env variable for username in deploy
          server-password: ${{ github.TOKEN }} # env variable for token in deploy
      - name: Construir y probar
        run: |
         mvn --batch-mode verify
         mkdir staging && cp target/*.jar staging
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
