name: Mulesoft CI Publish
on: 
  push:
    branches:  
      - main
env: 
   MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/mulesoft-github-actions"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: produccion
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - name: Construir y probar
        run: |
         mvn --batch-mode verify
         mkdir staging && cp target/*.jar staging
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }} # GITHUB_TOKEN is the default env for the password
      - name: Despliegue a desarrollo
        run: |
          mvn deploy -DmuleDeploy -DANYPOINT_TARGET=${{secrets.ANYPOINT_TARGET}} -DANYPOINT_TARGET_TYPE=${{secrets.ANYPOINT_TARGET_TYPE}} -DANYPOINT_USER=${{secrets.ANYPOINT_USER}} -DANYPOINT_PASSWORD=${{secrets.ANYPOINT_PASSWORD}} -DANYPOINT_ENV=${{secrets.ANYPOINT_ENV}} -DPARAMETRO_2=${{secrets.PARAMETRO_2}}
